### ISSUE TITLE
How to execute training process

### ISSUE THREAD

**Issue by Zhanghahah** [m-gallegos/SchNet4AIM#2]
Thanks for sharing. However, you did not mention how to execute the training process in your readme. Could you please add it. Thanks a lot!

**Comment by m-gallegos** [comment]
For information about the training process, please refer to the original SchNet (https://doi.org/10.1063/1.5019779) and SchNetPack (https://pubs.acs.org/doi/10.1021/acs.jctc.8b00908) papers, as well as the comprehensive supplementary material of SchNet4AIM (https://www.nature.com/articles/s41467-024-48567-9). The supplementary material offers extensive details on the various output modules, networks, and initialization specifically required to run SchNet4AIM.
